#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "TamilBotNew" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2ltc2FyYXZhbmFrcmlzaC9UYW1pbEJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d 
    elif [[ $UPSTREAM_REPO == "TamilBotOld" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2l2ZXRyaS9UYW1pbEJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2ltc2FyYXZhbmFrcmlzaC9UYW1pbEJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="tamil.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    TAMILPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $TAMILPATH
    echo "    Starting TamilBot    "
    echo "
            ::::::::::::::::::::::::::::::::::::::::::::::::::::::: 
            :#########..#####...####.....####..#########..##......: 
            ::. ##.... ##....## ##..#...#..##......##.....##......: 
            ::. ##.... ##....## ##...#::#..##......##.....##......: 
            ::. ##.... ######## ##....#....##......##.....##......: 
            ::. ##.... #.....## ##........ ##......##.....##......: 
            ::. ##.... #.....## ##........ ##......##.....##......: 
            ::. ##.... #.....## ##.........##..#########..#######.: 
            ::::::::::::::::::::::::::::::::::::::::::::::::::::::: 
    "

    echo "
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    :.##.....##...######...########..########    ########....#######...########:
    :.##.....##..##... ##..##........##.... ##   ##.....##..##.....##.... ##...:
    :.##.....##..##........##........##.... ##   ##.....##..##.....##.... ##...:
    :.##.....##...######:: ######....########    ########...##.....##.... ##...:
    :.##.....##....... ##: ##........##...##     ##.....##..##.....##.... ##...:
    :.##.....##..##... ##: ##........##... ##    ##.....##..##.....##.... ##...:
    :..######.....######: ########...##... ###   ########....#######......##...:
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    " 
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
